### ISSUE TITLE
Error when cv::mat at<int>(i,j)

### ISSUE THREAD

**Issue by anguoyang** [apennisi/fastestpedestriandetectorinthewest#2]
Hello, I have compiled the source code using visual studio/ intel c++ successfully, however, when run it, there was an error:
Unhandled exception at 0x76F796C2 in fpdw.exe: Microsoft C++ exception: cv::Exception at memory location 0x00AEE5AC.

and the broken point is here:
    CV_DbgAssert( dims <= 2 && data && (unsigned)i0 < (unsigned)size.p[0] &&
        (unsigned)(i1 \* DataType<_Tp>::channels) < (unsigned)(size.p[1] \* channels()) &&
        CV_ELEM_SIZE1(DataType<_Tp>::depth) == elemSize1());

which called by this:
    for(uint i = 0; i < indices.rows; ++i)
    {
        idx = indices.at<int>(0, i);/// get error here

**Comment by apennisi** [comment]
The detector has been tested only under linux and macos. I cannot help you because I did not test it under windows environment.  If you discover the error, please let me know and I will add the fix.

**Comment by anguoyang** [comment]
are you sure that the program could be run on Linux successfully?
could you please test this image:
http://www.jxhld.gov.cn/uploads/allimg/140526/565-1405261046304E.jpg

**Comment by apennisi** [comment]
Of course, I am sure. If you want to use my detector with another operating system, you have to solve the problems. I close this issue, even if I hoped that you can help me to realize a version for windows. But it seems that you are looking for something else.
P.S. Here there is your image processed with my detector under linux.
https://dl.dropboxusercontent.com/u/13194076/image_screenshot_21.10.2016.png

**Comment by anguoyang** [comment]
I have no rights to pull request on original rep, so I uploaded and created a new one:
https://github.com/anguoyang/fpdw4win

**Comment by apennisi** [comment]
Hi Jacky,

as you can read from the README file, the detector has been tested
(and developed) under linux, so I cannot help you.
All the other users, that have used my code, tested it under linux environment.

I am sorry about that.

Best Regards,
Andrea Pennisi

2016-10-21 11:13 GMT+02:00, Jacky Yang notifications@github.com:

> Hello, I have compiled the source code using visual studio/ intel c++
> successfully, however, when run it, there was an error:
> Unhandled exception at 0x76F796C2 in fpdw.exe: Microsoft C++ exception:
> cv::Exception at memory location 0x00AEE5AC.
> 
> and the broken point is here:
>     CV_DbgAssert( dims <= 2 && data && (unsigned)i0 < (unsigned)size.p[0]
> &&
>         (unsigned)(i1 \* DataType<_Tp>::channels) < (unsigned)(size.p[1] *
> channels()) &&
>         CV_ELEM_SIZE1(DataType<_Tp>::depth) == elemSize1());
> 
> which called by this:
>     for(uint i = 0; i < indices.rows; ++i)
>     {
>       idx = indices.at<int>(0, i);/// get error here
> 
> ## 
> 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/apennisi/fastestpedestriandetectorinthewest/issues/2

## 

Andrea Pennisi, Ph.D.
website: www.andreapennisi.com
